name: CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:

jobs:
  build-and-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.1 --activate

      - name: Install web deps
        working-directory: storyboard/apps/web
        run: pnpm install --frozen-lockfile=false

      - name: Build web
        working-directory: storyboard/apps/web
        run: pnpm build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install API deps
        working-directory: storyboard/apps/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API
        run: |
          nohup python -m uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 &
          sleep 2

      - name: Health check
        run: |
          curl -sSf http://localhost:8000/health | jq .
