name: storyboard
version: 0.1.0
apps:
  web:
    path: apps/web
    dev: pnpm dev
  api:
    path: apps/api
    dev: uvicorn apps.api.main:app --reload --host 0.0.0.0 --port 8000
workers:
  pdf:
    path: workers/pdf
    entry: workers/pdf/export.py
env_files:
  - .env.shared
  - .env.web.local
  - .env.api.local
